{
 "title": "sgx_daily_report ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 gainers",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sgx_data",
     "rawSql": "SELECT \r\n    Comm,\r\n    ROUND(100.0*(Close-Open)/Open,2) AS Pct_Change\r\nFROM fact_daily_summary\r\nORDER BY ROUND(100.0*(Close-Open)/Open,2) DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 losers",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "sgx_data",
     "rawSql": "SELECT \r\n    Comm,\r\n    ROUND(100.0*(Close-Open)/Open,2) AS Pct_Change\r\nFROM fact_daily_summary\r\nORDER BY ROUND(100.0*(Close-Open)/Open,2) ASC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Volume percent by trader types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sgx_data",
     "rawSql": "SELECT \r\n    Trader_Type,\r\n    SUM(Total_Volume) AS Total_Volume\r\nFROM fact_trade_distribution\r\nGROUP BY `Trader_Type`;"
    }
   ]
  },
  {
   "title": "Hourly stats ",
   "type": "trend",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "sgx_data",
     "rawSql": "SELECT \r\n    Hour,\r\n    SUM(Total_Volume) AS Total_Volume,\r\n    SUM(Total_Turnover) AS Total_Turnover\r\nFROM fact_hourly_stats\r\nGROUP BY Hour\r\nORDER BY 1 ASC;"
    }
   ]
  },
  {
   "title": "Trade_count percent by trader types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sgx_data",
     "rawSql": "SELECT \r\n    Trader_Type,\r\n    SUM(Trade_Count) AS Total_Count\r\nFROM fact_trade_distribution\r\nGROUP BY Trader_Type;"
    }
   ]
  }
 ]
}